Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -142,25 +142,25 @@ jobs:
                               if [ -z \$RSFROOT ]; then
                                 echo '### RSFROOT Missing ❌'
                               else
-                                echo '### RSFROOT: \$RSFROOT ✅'
+                                echo \"### RSFROOT: \$RSFROOT ✅\"
                               fi
                         
                               # Checa PYTHONPATH
                               if [ -z \$PYTHONPATH ]; then
                                 echo '### PYTHONPATH Missing ❌'
                               else
-                                echo '### PYTHONPATH: \$PYTHONPATH ✅'
+                                echo \"### PYTHONPATH: \$PYTHONPATH ✅\"
                               fi
                         
                               # Checa PATH
                               if ! echo \$PATH | grep -q \$RSFROOT/bin; then
                                 echo '### PATH problem: \$RSFROOT/bin not in PATH ❌'
                               else
-                                echo '### PATH OK: \$RSFROOT/bin is in PATH ✅'
+                                echo \"### PATH OK: \$RSFROOT/bin is in PATH ✅\"
                               fi
                         
                               # Testa Python e RSF
-                              python3 -c 'import rsf' && echo '### Python RSF: Import successful ✅' || echo '### Python RSF: Import FAILED ❌'
+                              python3 -c 'import rsf' && echo \"### Python RSF: Import successful ✅\" || echo \"### Python RSF: Import FAILED ❌\"
                             " >> $GITHUB_STEP_SUMMARY
 
                         - name: Run unit tests in Madagascar 3.0
